//! Fortolkning — one interpretation per metric, written once here and served with the data so
//! every page shows the same tip beside the same number. Each tip says three things: what the
//! number is, how to read it today, and what it is NOT (the honest half).

use serde_json::{json, Value};

pub fn tips() -> Value {
    json!({
        "k_resid": {
            "name": "K⊕ (de-wobbled)",
            "what": "How far today's rotation vector sits from where the known cycles said it would be, in residual σ: the pole (x_p, y_p) after trend + annual + semiannual + Chandler 433 d, and the day length after trend + annual + semiannual, combined in quadrature like a χ with three degrees of freedom.",
            "read": "Below 1: Earth is doing what the model expects. 1–3: one of the three is a bit off, usually the day length after a storm season or an ENSO shift. Above the p99 line: something the model does not know about happened — that is the alert.",
            "not": "It is not a forecast of earthquakes or weather, and it is not the raw pole offset. It is the surprise, not the size.",
            "family": "Same shape as the chain's K_fix: a disagreement term (residual/σ) inside a square root. Here the three channels are geophysical, not consensus channels."
        },
        "k_raw": {
            "name": "K⊕ raw",
            "what": "The same three quantities scored against the plain mean and spread of the trailing year, with no cycles removed.",
            "read": "It sits above 1 most of the time because the Chandler and annual wobbles alone move the pole by metres. That is the point: it shows what the de-wobbling takes out.",
            "not": "Not the headline number. A high K_raw with a low K_resid means 'big but expected'."
        },
        "ladder": {
            "name": "The ladder",
            "what": "Empirical quantiles of K⊕ over the trailing three years (p50 / p90 / p99 / max), beside the χ₃ values a Gaussian would give (1.54 / 2.50 / 3.37).",
            "read": "Compare today's K⊕ to the p99: above it, the alert fires; between p90 and p99, watch. If the empirical p99 sits well above 3.37, the residuals have fat tails and the model is missing a cycle.",
            "not": "Not a fixed scale. It moves as the window moves."
        },
        "xp": {"name": "x_p", "what": "Where the rotation axis pierces the crust, in arcseconds toward the Greenwich meridian (IERS convention). 1″ ≈ 30.9 m on the ground.", "read": "Follows a ~14-month spiral (Chandler wobble) mixed with an annual loop; the model_xp line is that spiral. The gap between the two is what K⊕ scores.", "not": "Not the geographic pole moving in any everyday sense: the whole excursion is a few metres."},
        "yp": {"name": "y_p", "what": "The other pole coordinate, toward 90° West (IERS convention). In the right-handed frame the page uses, ω_y = −Ω₀·y_p.", "read": "Read it with x_p as one point on the polhode. The dashed forecast path is the IERS prediction of where that point goes next.", "not": "Its sign is a convention; only the distance from the model matters for K⊕."},
        "lod": {"name": "LOD", "what": "Excess length of day over 86 400 s, in milliseconds. Positive: the day is longer than nominal, Earth spins slower.", "read": "Seasonal ±0.5 ms from the atmosphere, a 13.66 d and 27.55 d tidal ripple of ±0.5 ms, and slow decadal swings from the core. Today's value beside the fluid estimate tells you how much of it is weather.", "not": "It is not a trend: the secular tidal braking is ~2 ms per century, invisible at this scale."},
        "ut1utc": {"name": "UT1−UTC", "what": "How far the Earth-angle clock (UT1) has drifted from atomic UTC, in seconds. Its slope is −LOD.", "read": "Approaching ±0.9 s forces a leap second; the current drift toward zero from below is why a negative leap second has been discussed. The 3D globe is turned by this number.", "not": "Not a measurement of the day length directly; the day length is its derivative."},
        "omega": {"name": "ω vector", "what": "The rotation vector in rad/s: ω_x, ω_y from the pole offset, ω_z from the day length. Nominal Ω₀ = 7.292115e-5 rad/s.", "read": "ω_z − Ω₀ is of order 1e-13 rad/s — one part in a billion. The picture is exact; the deviation is tiny and real.", "not": "Not the axis of figure (the crust's symmetry axis): the small angle between the two is the polar motion."},
        "pole_offset_m": {"name": "Pole offset", "what": "Distance on the crust between the instantaneous rotation pole and the reference pole, R⊕·√(x_p²+y_p²).", "read": "Typically 3–15 m, a spiral with a ~6.4-year beat between the annual and Chandler terms. On the globe it is exaggerated ×20 000 and labelled so.", "not": "Not a drift of the continents; the reference pole is fixed to the crust."},
        "E_rot_J": {"name": "Rotational energy", "what": "½·I·ω² with I = 8.034e37 kg·m² (assumed constant).", "read": "About 2.1e29 J. A 1 ms longer day removes about 5e21 J from it — the dE per ms figure — which is roughly the world's annual energy use, moved into or out of the fluids and the core.", "not": "Not an energy the fluids 'consume'; it is exchanged as angular momentum."},
        "L_kg_m2_s": {"name": "Angular momentum", "what": "I·ω, about 5.9e33 kg·m²/s. Conserved for the Earth system: what the atmosphere gains, the solid Earth loses.", "read": "That conservation is why AAM predicts LOD: a westerly wind burst spins the air up and the ground down by the same amount.", "not": "Not conserved for the solid Earth alone."},
        "equator_speed_m_s": {"name": "Equator speed", "what": "ω_z·R⊕, about 465 m/s.", "read": "Changes by ~5 µm/s per ms of LOD. Shown to give the vector a human scale.", "not": "Not a measurement; a derived number."},
        "lod_atm_ms": {"name": "Atmosphere (AAM)", "what": "GFZ's effective angular momentum of the atmosphere (ECMWF winds + pressure) converted to a length-of-day change: 86 400 s × χ₃, in ms.", "read": "Carries most of the seasonal LOD signal: the northern winter jet streams spin the air up and the day lengthens.", "not": "A model product, not a measurement. It has no tides in it."},
        "lod_ocn_ms": {"name": "Ocean (OAM)", "what": "The same from the MPIOM ocean model (currents + bottom pressure).", "read": "Small but not negligible at the seasonal scale; strongest during ENSO events.", "not": "Model product."},
        "lod_hyd_ms": {"name": "Land water (HAM)", "what": "The same from the LSDM land-hydrology model (soil moisture, snow, rivers).", "read": "Slow and small in LOD; it matters more for the pole (χ₁, χ₂) than for the day length.", "not": "Model product."},
        "lod_geo_ms": {"name": "Fluids, total", "what": "Atmosphere + ocean + land water, ms of LOD.", "read": "Put beside the observed LOD after the 31-day smoothing: R² 0.7 means seven tenths of the season-to-season day-length change IS the fluids. The rest is the core and model error.", "not": "It cannot explain the tidal ripple (the models do not carry tides), which is why the daily R² is low."},
        "attribution_r2": {"name": "R² attribution", "what": "How much of the observed LOD variance the fluid estimate explains, daily and after a 31-day running mean.", "read": "Daily R² is dragged down by the zonal tides; the smoothed R² is the fair number. Both are reported so nobody has to trust the choice.", "not": "Not a fit of the fluids to LOD; the slope and offset only calibrate the models' subtracted mean."},
        "k_resid_fcst": {"name": "K⊕ forecast", "what": "The IERS-predicted pole and UT1−UTC for the next ten days, pushed through the same model and σ as today's K⊕. LOD on those days is the finite difference of the predicted UT1−UTC, because prediction rows carry no LOD.", "read": "Trust the first three days; after that the IERS pole prediction and the fluid forecast both lose skill. The band is the IERS-stated prediction error propagated.", "not": "It is not our own prediction of the pole; it is a reading of the IERS prediction through our model."},
        "k_resid_fcst_gfz": {"name": "K⊕ forecast, fluid opinion", "what": "The same K⊕ with the LOD slot filled by the GFZ 10-day fluid forecast (calibrated), instead of the IERS UT1−UTC difference.", "read": "Two independent forecasts of the same number. When they agree, believe both; when they split, the gap is the tides plus the core.", "not": "Never averaged into the headline forecast."},
        "eam90": {"name": "±90-day EAM prediction", "what": "GFZ's combined atmosphere + ocean + hydrology prediction three months out (Dill et al. 2018).", "read": "Useful for the direction of the seasonal swing, not its daily value.", "not": "Not a forecast of K⊕; it feeds only the LOD channel."},
        "era": {"name": "Earth Rotation Angle", "what": "The angle the globe has turned since the reference epoch, from your clock plus UT1−UTC: ERA = 2π(0.7790572732640 + 1.00273781191135448·(JD_UT1 − 2451545)).", "read": "The 3D globe is turned by exactly this, so Greenwich sits where it really is right now and the terminator is where the Sun really puts it.", "not": "Not sidereal time (that adds precession); the difference is under a degree."},
        "attest": {"name": "Attestation", "what": "BLAKE3 of the exact bytes of latest.json, chained to the previous digest and signed with a dedicated Ed25519 key. An anchor row records the shielded SIGIL transaction that carried the digest in its memo.", "read": "Anyone can recompute the digest from the published file and check the signature against the published key. The chain receipt proves the digest existed at that block; it does not prove the reading is true.", "not": "Not a proof of correctness; a proof of non-alteration with a timestamp nobody can rewrite."},
        "alert": {"name": "Alert", "what": "K⊕ above the empirical p99 of the trailing three years (fires once, re-arms below p90), or a step on the K-family ladder.", "read": "One alert means: look at the fluids panel first. If the fluid estimate also jumped, it is weather; if not, it is the core or a data revision.", "not": "Not an earthquake or weather warning. IERS rapid values are revised for weeks; an alert can be revised away."}
    })
}
