//! PV-1 END-TO-END: transparent → shielded → spend, through the real chokepoint.
//!
//! Every other test in this effort exercises one layer. This one drives the whole path a
//! real transaction takes — `Shield` debits a wallet and appends a note, the pool publishes
//! an anchor, a REAL winterfell proof is produced against that anchor, and
//! `commit_state_transition` verifies it before mutating anything. Then it attacks the same
//! path four ways and requires each attack to be refused.
//!
//! The point is that no layer is trusted here. The proof is not asserted to be valid; it is
//! generated by the prover and checked by the verifier the chokepoint calls.

use sigil_shield::mimc::{compress2, mimc_options};
use sigil_shield::note_v1::{padding_leaf, to_wire, Note, ShieldedPoolTree};
use sigil_shield::spend_full_v2::{
    build_spend_full_v2_trace, SpendFullV2Prover, N_OUTS,
};
use sigil_state::shielded::POOL_CAPACITY;
use sigil_state::{
    commit_state_transition, CommitError, SigilState, StateMutation, StateTransition, NATIVE,
};
use winterfell::math::fields::f64::BaseElement;
use winterfell::Prover;

fn e(v: u64) -> BaseElement {
    BaseElement::new(v)
}

const ALICE: [u8; 32] = [0xA1; 32];
const MASTER: [u8; 32] = [0x11; 32];

/// Drive one transition at `height`, returning the chokepoint's verdict.
fn apply(
    state: &mut SigilState,
    height: u64,
    mutations: Vec<StateMutation>,
) -> Result<(), CommitError> {
    commit_state_transition(
        state,
        &StateTransition { at_height: height, mutations },
        height,
    )
    .map(|_| ())
}

/// Fund Alice, set the master wallet, and shield `value` into a note at a known position.
/// Returns (state, note, position, anchor).
fn shielded_fixture(value: u64, blinding: u64, key: u64) -> (SigilState, Note, usize, [u8; 32]) {
    let mut state = SigilState::default();
    let note = Note::new(value, blinding, key).expect("in range");

    apply(
        &mut state,
        1,
        vec![
            StateMutation::SetMasterWallet { wallet: MASTER },
            StateMutation::SetBalance { wallet: ALICE, token: NATIVE, amount: value as u128 },
        ],
    )
    .expect("genesis funding");

    apply(
        &mut state,
        2,
        vec![StateMutation::Shield {
            from: ALICE,
            amount: value as u128,
            cm: to_wire(note.commitment()),
        }],
    )
    .expect("shield must succeed");

    // Alice's transparent balance is gone; the value is locked in the pool.
    assert_eq!(state.balance_of(&ALICE, &NATIVE), 0, "shield must debit transparently");
    assert_eq!(state.shielded().value_locked(), value as u128, "value crossed domains");
    assert_eq!(state.shielded().len(), 1, "one note in the pool");

    let position = 0usize;
    let anchor = state.shielded().current_root();
    (state, note, position, anchor)
}

/// The off-circuit pool the prover proves against — identical padding to what the pool
/// itself uses, which is the whole reason `padding_leaf` is shared rather than reinvented.
fn prover_pool(note: &Note) -> ShieldedPoolTree {
    let mut leaves = vec![note.commitment()];
    for i in leaves.len()..POOL_CAPACITY {
        leaves.push(padding_leaf(i as u64));
    }
    ShieldedPoolTree::new(leaves).expect("prover pool")
}

/// Produce a real spend proof for `note` at `position`, spending `fee + outs`.
fn prove_spend(
    note: &Note,
    position: usize,
    fee: BaseElement,
    outs: &[(BaseElement, BaseElement); N_OUTS],
) -> (Vec<u8>, [u8; 32], Vec<[u8; 32]>) {
    let pool = prover_pool(note);
    let path = pool.path(position);
    let trace =
        build_spend_full_v2_trace(note.value, note.blinding, note.spend_key, fee, outs, &path);
    let proof = SpendFullV2Prover::new(mimc_options())
        .prove(trace)
        .expect("prover must produce a proof for an honest witness");
    let nf = to_wire(note.nullifier(position as u64));
    let cm_outs: Vec<[u8; 32]> =
        outs.iter().map(|(v, b)| to_wire(compress2(*v, *b))).collect();
    (proof.to_bytes(), nf, cm_outs)
}

/// THE HAPPY PATH: a real proof, verified by the chokepoint, mutating real state.
#[test]
fn shield_then_spend_is_accepted_and_mutates_state() {
    let (mut state, note, position, anchor) = shielded_fixture(100, 4242, 0xDEAD);

    // The pool's own root must equal the one the prover builds — if these ever diverge,
    // no honest spend can ever verify.
    assert_eq!(anchor, to_wire(prover_pool(&note).root()), "pool root must match prover's");

    let fee = e(3);
    let outs = [(e(50), e(777)), (e(47), e(888))];
    let (proof, nf, cm_outs) = prove_spend(&note, position, fee, &outs);

    apply(
        &mut state,
        3,
        vec![StateMutation::ShieldedSpend {
            anchor,
            nullifier: nf,
            cm_outs: cm_outs.clone(),
            fee: 3,
            proof,
        }],
    )
    .expect("an honest shielded spend must be accepted");

    assert!(state.shielded().is_spent(&nf), "nullifier must be recorded");
    assert_eq!(state.shielded().len(), 3, "one input note + two new outputs");
    assert_eq!(
        state.balance_of(&MASTER, &NATIVE),
        3,
        "the public fee must be credited transparently"
    );
    assert_eq!(
        state.shielded().value_locked(),
        97,
        "the fee left the shielded domain; the rest stays locked"
    );
}

/// DOUBLE-SPEND: the same nullifier twice. The second must be refused even though the
/// proof is genuinely valid — validity is not freshness.
#[test]
fn replaying_a_nullifier_is_refused() {
    let (mut state, note, position, anchor) = shielded_fixture(100, 4242, 0xDEAD);
    let fee = e(3);
    let outs = [(e(50), e(777)), (e(47), e(888))];
    let (proof, nf, cm_outs) = prove_spend(&note, position, fee, &outs);

    let spend = |p: Vec<u8>| StateMutation::ShieldedSpend {
        anchor,
        nullifier: nf,
        cm_outs: cm_outs.clone(),
        fee: 3,
        proof: p,
    };

    apply(&mut state, 3, vec![spend(proof.clone())]).expect("first spend ok");
    let locked_before = state.shielded().value_locked();

    let err = apply(&mut state, 4, vec![spend(proof)]).expect_err("SECURITY: replay must fail");
    assert!(
        matches!(err, CommitError::Shielded(_)),
        "expected a shielded double-spend error, got {err:?}"
    );
    assert_eq!(
        state.shielded().value_locked(),
        locked_before,
        "a refused spend must not mutate value"
    );
}

/// FORGED ANCHOR: proving against a tree the pool never held would let an attacker invent
/// a note of any value. The chokepoint must refuse the anchor before it even proves.
#[test]
fn unknown_anchor_is_refused() {
    let (mut state, note, position, _anchor) = shielded_fixture(100, 4242, 0xDEAD);
    let fee = e(3);
    let outs = [(e(50), e(777)), (e(47), e(888))];
    let (proof, nf, cm_outs) = prove_spend(&note, position, fee, &outs);

    let err = apply(
        &mut state,
        3,
        vec![StateMutation::ShieldedSpend {
            anchor: [0xAB; 32], // a root this pool never had
            nullifier: nf,
            cm_outs,
            fee: 3,
            proof,
        }],
    )
    .expect_err("SECURITY: an unknown anchor must be refused");
    assert!(matches!(err, CommitError::UnknownAnchor { .. }), "got {err:?}");
    assert!(!state.shielded().is_spent(&nf), "a refused spend must not burn the nullifier");
}

/// TAMPERED PROOF: flipping a byte must not survive verification.
#[test]
fn tampered_proof_is_refused() {
    let (mut state, note, position, anchor) = shielded_fixture(100, 4242, 0xDEAD);
    let fee = e(3);
    let outs = [(e(50), e(777)), (e(47), e(888))];
    let (mut proof, nf, cm_outs) = prove_spend(&note, position, fee, &outs);

    let mid = proof.len() / 2;
    proof[mid] ^= 0xFF;

    let err = apply(
        &mut state,
        3,
        vec![StateMutation::ShieldedSpend { anchor, nullifier: nf, cm_outs, fee: 3, proof }],
    )
    .expect_err("SECURITY: a tampered proof must be refused");
    assert!(
        matches!(err, CommitError::ShieldedProofRejected { .. }),
        "expected proof rejection, got {err:?}"
    );
}

/// THE MINT VECTOR, at the chokepoint. The spend is honest and the proof is real, but the
/// mutation claims commitments to inflated outputs. `spend_full_v2` binds `cm_out` to the
/// conserved amount in-circuit, so the verifier must refuse — this is the whole reason the
/// v2 circuit exists, checked here at the layer that actually moves money.
#[test]
fn inflated_output_commitments_are_refused_at_the_chokepoint() {
    let (mut state, note, position, anchor) = shielded_fixture(100, 4242, 0xDEAD);
    let fee = e(3);
    let honest = [(e(50), e(777)), (e(47), e(888))];
    let (proof, nf, _real) = prove_spend(&note, position, fee, &honest);

    // Claim notes worth 10× what was actually conserved.
    let inflated = vec![
        to_wire(compress2(e(500), e(777))),
        to_wire(compress2(e(470), e(888))),
    ];

    let err = apply(
        &mut state,
        3,
        vec![StateMutation::ShieldedSpend {
            anchor,
            nullifier: nf,
            cm_outs: inflated,
            fee: 3,
            proof,
        }],
    )
    .expect_err("SECURITY: inflated output commitments must be refused — this is a mint vector");
    assert!(
        matches!(err, CommitError::ShieldedProofRejected { .. }),
        "expected proof rejection, got {err:?}"
    );
    assert_eq!(state.shielded().len(), 1, "no notes may be appended by a refused spend");
}

/// THEFT VECTOR: an unshield with no valid proof must be refused.
///
/// Without a proof binding `(nullifier, amount)` to a note the caller owns, naming any
/// nullifier would be enough to withdraw from the pool — the locked-value check alone
/// only caps the theft at the pool's size, it does not prevent it.
#[test]
fn unproven_unshield_is_refused() {
    let (mut state, _note, _pos, anchor) = shielded_fixture(100, 4242, 0xDEAD);
    let err = apply(
        &mut state,
        3,
        vec![StateMutation::Unshield {
            to: ALICE,
            amount: 50,
            anchor,
            nullifier: [0x5A; 32], // a nullifier for no note the caller owns
            cm_outs: vec![[0u8; 32], [0u8; 32]],
            proof: vec![0u8; 32], // garbage
        }],
    )
    .expect_err("SECURITY: an unshield without a valid proof must be refused");
    assert!(matches!(err, CommitError::ShieldedProofRejected { .. }), "got {err:?}");
    assert_eq!(state.balance_of(&ALICE, &NATIVE), 0, "no credit on a refused unshield");
    assert_eq!(state.shielded().value_locked(), 100, "pool must be untouched");
}

/// AN HONEST UNSHIELD round-trips: value leaves the pool and lands transparently.
#[test]
fn proven_unshield_returns_value_transparently() {
    let (mut state, note, position, anchor) = shielded_fixture(100, 4242, 0xDEAD);

    // Withdraw 100 publicly, with two zero-value change notes.
    let amount = e(100);
    let outs = [(e(0), e(777)), (e(0), e(888))];
    let (proof, nf, cm_outs) = prove_spend(&note, position, amount, &outs);

    apply(
        &mut state,
        3,
        vec![StateMutation::Unshield {
            to: ALICE,
            amount: 100,
            anchor,
            nullifier: nf,
            cm_outs,
            proof,
        }],
    )
    .expect("an honest, proven unshield must be accepted");

    assert_eq!(state.balance_of(&ALICE, &NATIVE), 100, "value returned transparently");
    assert_eq!(state.shielded().value_locked(), 0, "pool drained of that note's value");
    assert!(state.shielded().is_spent(&nf), "nullifier consumed");
}

/// An unshield may never return more than the pool holds, even with a valid proof shape.
#[test]
fn unshield_cannot_overdraw_the_pool() {
    let (mut state, note, position, anchor) = shielded_fixture(100, 4242, 0xDEAD);
    // Prove a spend of the real note, then claim a LARGER withdrawal than it was worth.
    let amount = e(100);
    let outs = [(e(0), e(777)), (e(0), e(888))];
    let (proof, nf, cm_outs) = prove_spend(&note, position, amount, &outs);

    let err = apply(
        &mut state,
        3,
        vec![StateMutation::Unshield {
            to: ALICE,
            amount: 1_000, // the proof commits to 100, not 1000
            anchor,
            nullifier: nf,
            cm_outs,
            proof,
        }],
    )
    .expect_err("SECURITY: withdrawing more than the proof commits to would mint");
    // The proof binds the public amount, so this is caught at verification.
    assert!(
        matches!(err, CommitError::ShieldedProofRejected { .. }),
        "got {err:?}"
    );
    assert_eq!(state.balance_of(&ALICE, &NATIVE), 0, "no credit on a refused unshield");
}

/// PERSISTENCE: the shielded pool must survive the snapshot round-trip.
///
/// The node persists state with `rmp_serde` (MessagePack). A pool that serialized but
/// came back wrong would be worse than one that failed to serialize: notes would silently
/// vanish, anchors would stop matching, and every honest spend would be rejected as
/// "unknown anchor" with nothing to point at. So this asserts the CONTENTS survive, not
/// merely that encode/decode returns Ok — and then re-verifies a real spend against the
/// restored anchor, which is the only proof that the restored pool is actually usable.
#[test]
fn shielded_pool_survives_the_snapshot_round_trip() {
    let (state, note, position, anchor) = shielded_fixture(100, 4242, 0xDEAD);

    let bytes = rmp_serde::to_vec(&state).expect("snapshot encode");
    let mut restored: SigilState = rmp_serde::from_slice(&bytes).expect("snapshot decode");

    let a = state.shielded();
    let b = restored.shielded();
    assert_eq!(b.len(), a.len(), "note count must survive");
    assert_eq!(b.note_at(0), a.note_at(0), "the note commitment itself must survive");
    assert_eq!(b.value_locked(), a.value_locked(), "locked value must survive");
    assert_eq!(b.nullifier_count(), a.nullifier_count(), "spent set must survive");
    assert!(
        b.is_known_anchor(&anchor),
        "the anchor window must survive — otherwise every pending spend fails as unknown-anchor"
    );
    assert_eq!(b.current_root(), a.current_root(), "the recomputed root must match");

    // The restored pool must be USABLE, not merely equal: prove a real spend against it.
    let fee = e(3);
    let outs = [(e(50), e(777)), (e(47), e(888))];
    let (proof, nf, cm_outs) = prove_spend(&note, position, fee, &outs);
    apply(
        &mut restored,
        3,
        vec![StateMutation::ShieldedSpend { anchor, nullifier: nf, cm_outs, fee: 3, proof }],
    )
    .expect("a spend must still verify against a restored anchor");
    assert!(restored.shielded().is_spent(&nf));
}
