//! PV-1 END-TO-END: transparent → shielded → spend, through the real chokepoint.
//!
//! Every other test in this effort exercises one layer. This one drives the whole path a
//! real transaction takes — `Shield` debits a wallet and appends a note, the pool publishes
//! an anchor, a REAL winterfell proof is produced against that anchor, and
//! `commit_state_transition` verifies it before mutating anything. Then it attacks the same
//! path four ways and requires each attack to be refused.
//!
//! The point is that no layer is trusted here. The proof is not asserted to be valid; it is
//! generated by the prover and checked by the verifier the chokepoint calls.

use sigil_shield::mimc::{compress2, mimc_options};
use sigil_shield::note_v1::{padding_leaf, to_wire, Note, ShieldedPoolTree};
use sigil_shield::spend_full_v4::{build_spend_full_v4_trace, SpendFullV4Prover, N_OUTS};
use sigil_state::shielded::{POOL_CAPACITY, SHIELDED_FEE};
use sigil_state::{
    commit_state_transition, CommitError, SigilState, StateMutation, StateTransition, NATIVE,
};
use winterfell::math::fields::f64::BaseElement;
use winterfell::Prover;

fn e(v: u64) -> BaseElement {
    BaseElement::new(v)
}

const ALICE: [u8; 32] = [0xA1; 32];
const MASTER: [u8; 32] = [0x11; 32];

/// Drive one transition at `height`, returning the chokepoint's verdict.
fn apply(
    state: &mut SigilState,
    height: u64,
    mutations: Vec<StateMutation>,
) -> Result<(), CommitError> {
    commit_state_transition(
        state,
        &StateTransition { at_height: height, mutations },
        height,
    )
    .map(|_| ())
}

/// Fund Alice, set the master wallet, and shield `value` into a note at a known position.
/// Returns (state, note, position, anchor).
fn shielded_fixture(value: u64, blinding: u64, key: u64) -> (SigilState, Note, usize, [u8; 32]) {
    let mut state = SigilState::default();
    let note = Note::new(value, blinding, key).expect("in range");

    apply(
        &mut state,
        1,
        vec![
            StateMutation::SetMasterWallet { wallet: MASTER },
            StateMutation::SetBalance { wallet: ALICE, token: NATIVE, amount: value as u128 },
        ],
    )
    .expect("genesis funding");

    apply(
        &mut state,
        2,
        vec![StateMutation::Shield {
            from: ALICE,
            amount: value as u128,
            cm: to_wire(note.commitment()),
        }],
    )
    .expect("shield must succeed");

    // Alice's transparent balance is gone; the value is locked in the pool.
    assert_eq!(state.balance_of(&ALICE, &NATIVE), 0, "shield must debit transparently");
    assert_eq!(state.shielded().value_locked(), value as u128, "value crossed domains");
    assert_eq!(state.shielded().len(), 1, "one note in the pool");

    let position = 0usize;
    let anchor = state.shielded().current_root();
    (state, note, position, anchor)
}

/// The off-circuit pool the prover proves against — identical padding to what the pool
/// itself uses, which is the whole reason `padding_leaf` is shared rather than reinvented.
fn prover_pool(note: &Note) -> ShieldedPoolTree {
    let mut leaves = vec![note.commitment()];
    for i in leaves.len()..POOL_CAPACITY {
        leaves.push(padding_leaf(i as u64));
    }
    ShieldedPoolTree::new(leaves).expect("prover pool")
}

/// Produce a real spend proof for `note` at `position`, spending `fee + outs`.
fn prove_spend(
    note: &Note,
    position: usize,
    fee: BaseElement,
    outs: &[(BaseElement, BaseElement); N_OUTS],
) -> (Vec<u8>, [u8; 32], Vec<[u8; 32]>) {
    let pool = prover_pool(note);
    let path = pool.path(position);
    // Change notes go back to the spender: bind them to the spender's own key. An
    // un-owned output would be spendable by anyone who learned its preimage.
    let me = note.owner_pk();
    let bound: [(BaseElement, BaseElement, BaseElement); N_OUTS] =
        [(outs[0].0, outs[0].1, me), (outs[1].0, outs[1].1, me)];
    let trace =
        build_spend_full_v4_trace(note.value, note.blinding, note.spend_key, fee, &bound, &path);
    let proof = SpendFullV4Prover::new(mimc_options())
        .prove(trace)
        .expect("prover must produce a proof for an honest witness");
    let nf = to_wire(note.nullifier(position as u64));
    let cm_outs: Vec<[u8; 32]> = bound
        .iter()
        .map(|(v, b, pk)| to_wire(compress2(compress2(*v, *b), *pk)))
        .collect();
    (proof.to_bytes(), nf, cm_outs)
}

/// THE HAPPY PATH: a real proof, verified by the chokepoint, mutating real state.
#[test]
fn shield_then_spend_is_accepted_and_mutates_state() {
    let (mut state, note, position, anchor) = shielded_fixture(10_000, 4242, 0xDEAD);

    // The pool's own root must equal the one the prover builds — if these ever diverge,
    // no honest spend can ever verify.
    assert_eq!(anchor, to_wire(prover_pool(&note).root()), "pool root must match prover's");

    let fee = e(SHIELDED_FEE as u64);
    let outs = [(e(5_000), e(777)), (e(4_000), e(888))];
    let (proof, nf, cm_outs) = prove_spend(&note, position, fee, &outs);

    apply(
        &mut state,
        3,
        vec![StateMutation::ShieldedSpend {
            anchor,
            nullifier: nf,
            cm_outs: cm_outs.clone(),
            fee: SHIELDED_FEE,
            proof,
            note_ciphertexts: vec![],
        }],
    )
    .expect("an honest shielded spend must be accepted");

    assert!(state.shielded().is_spent(&nf), "nullifier must be recorded");
    assert_eq!(state.shielded().len(), 3, "one input note + two new outputs");
    assert_eq!(
        state.balance_of(&MASTER, &NATIVE),
        SHIELDED_FEE,
        "the public fee must be credited transparently"
    );
    assert_eq!(
        state.shielded().value_locked(),
        10_000 - SHIELDED_FEE,
        "the fee left the shielded domain; the rest stays locked"
    );
}

/// DOUBLE-SPEND: the same nullifier twice. The second must be refused even though the
/// proof is genuinely valid — validity is not freshness.
#[test]
fn replaying_a_nullifier_is_refused() {
    let (mut state, note, position, anchor) = shielded_fixture(10_000, 4242, 0xDEAD);
    let fee = e(SHIELDED_FEE as u64);
    let outs = [(e(5_000), e(777)), (e(4_000), e(888))];
    let (proof, nf, cm_outs) = prove_spend(&note, position, fee, &outs);

    let spend = |p: Vec<u8>| StateMutation::ShieldedSpend {
        anchor,
        nullifier: nf,
        cm_outs: cm_outs.clone(),
        fee: SHIELDED_FEE,
        proof: p,
        note_ciphertexts: vec![],
    };

    apply(&mut state, 3, vec![spend(proof.clone())]).expect("first spend ok");
    let locked_before = state.shielded().value_locked();

    let err = apply(&mut state, 4, vec![spend(proof)]).expect_err("SECURITY: replay must fail");
    assert!(
        matches!(err, CommitError::Shielded(_)),
        "expected a shielded double-spend error, got {err:?}"
    );
    assert_eq!(
        state.shielded().value_locked(),
        locked_before,
        "a refused spend must not mutate value"
    );
}

/// FORGED ANCHOR: proving against a tree the pool never held would let an attacker invent
/// a note of any value. The chokepoint must refuse the anchor before it even proves.
#[test]
fn unknown_anchor_is_refused() {
    let (mut state, note, position, _anchor) = shielded_fixture(10_000, 4242, 0xDEAD);
    let fee = e(SHIELDED_FEE as u64);
    let outs = [(e(5_000), e(777)), (e(4_000), e(888))];
    let (proof, nf, cm_outs) = prove_spend(&note, position, fee, &outs);

    let err = apply(
        &mut state,
        3,
        vec![StateMutation::ShieldedSpend {
            anchor: [0xAB; 32], // a root this pool never had
            nullifier: nf,
            cm_outs,
            fee: SHIELDED_FEE,
            proof,
            note_ciphertexts: vec![],
        }],
    )
    .expect_err("SECURITY: an unknown anchor must be refused");
    assert!(matches!(err, CommitError::UnknownAnchor { .. }), "got {err:?}");
    assert!(!state.shielded().is_spent(&nf), "a refused spend must not burn the nullifier");
}

/// TAMPERED PROOF: flipping a byte must not survive verification.
#[test]
fn tampered_proof_is_refused() {
    let (mut state, note, position, anchor) = shielded_fixture(10_000, 4242, 0xDEAD);
    let fee = e(SHIELDED_FEE as u64);
    let outs = [(e(5_000), e(777)), (e(4_000), e(888))];
    let (mut proof, nf, cm_outs) = prove_spend(&note, position, fee, &outs);

    let mid = proof.len() / 2;
    proof[mid] ^= 0xFF;

    let err = apply(
        &mut state,
        3,
        vec![StateMutation::ShieldedSpend { anchor, nullifier: nf, cm_outs, fee: SHIELDED_FEE, proof, note_ciphertexts: vec![] }],
    )
    .expect_err("SECURITY: a tampered proof must be refused");
    assert!(
        matches!(err, CommitError::ShieldedProofRejected { .. }),
        "expected proof rejection, got {err:?}"
    );
}

/// THE MINT VECTOR, at the chokepoint. The spend is honest and the proof is real, but the
/// mutation claims commitments to inflated outputs. `spend_full_v4` binds `cm_out` to the
/// conserved amount in-circuit, so the verifier must refuse — this is the whole reason the
/// v2 circuit exists, checked here at the layer that actually moves money.
#[test]
fn inflated_output_commitments_are_refused_at_the_chokepoint() {
    let (mut state, note, position, anchor) = shielded_fixture(10_000, 4242, 0xDEAD);
    let fee = e(SHIELDED_FEE as u64);
    let honest = [(e(5_000), e(777)), (e(4_000), e(888))];
    let (proof, nf, _real) = prove_spend(&note, position, fee, &honest);

    // Claim notes worth 10× what was actually conserved.
    let me = note.owner_pk();
    let inflated = vec![
        to_wire(compress2(compress2(e(50_000), e(777)), me)),
        to_wire(compress2(compress2(e(40_000), e(888)), me)),
    ];

    let err = apply(
        &mut state,
        3,
        vec![StateMutation::ShieldedSpend {
            anchor,
            nullifier: nf,
            cm_outs: inflated,
            fee: SHIELDED_FEE,
            proof,
            note_ciphertexts: vec![],
        }],
    )
    .expect_err("SECURITY: inflated output commitments must be refused — this is a mint vector");
    assert!(
        matches!(err, CommitError::ShieldedProofRejected { .. }),
        "expected proof rejection, got {err:?}"
    );
    assert_eq!(state.shielded().len(), 1, "no notes may be appended by a refused spend");
}

/// THEFT VECTOR: an unshield with no valid proof must be refused.
///
/// Without a proof binding `(nullifier, amount)` to a note the caller owns, naming any
/// nullifier would be enough to withdraw from the pool — the locked-value check alone
/// only caps the theft at the pool's size, it does not prevent it.
#[test]
fn unproven_unshield_is_refused() {
    let (mut state, _note, _pos, anchor) = shielded_fixture(10_000, 4242, 0xDEAD);
    let err = apply(
        &mut state,
        3,
        vec![StateMutation::Unshield {
            to: ALICE,
            amount: 10_000,
            anchor,
            nullifier: [0x5A; 32], // a nullifier for no note the caller owns
            cm_outs: vec![[0u8; 32], [0u8; 32]],
            proof: vec![0u8; 32], // garbage
        }],
    )
    .expect_err("SECURITY: an unshield without a valid proof must be refused");
    assert!(matches!(err, CommitError::ShieldedProofRejected { .. }), "got {err:?}");
    assert_eq!(state.balance_of(&ALICE, &NATIVE), 0, "no credit on a refused unshield");
    assert_eq!(state.shielded().value_locked(), 10_000, "pool must be untouched");
}

/// AN HONEST UNSHIELD round-trips: value leaves the pool and lands transparently.
#[test]
fn proven_unshield_returns_value_transparently() {
    let (mut state, note, position, anchor) = shielded_fixture(10_000, 4242, 0xDEAD);

    // Withdraw 100 publicly, with two zero-value change notes.
    let amount = e(10_000);
    let outs = [(e(0), e(777)), (e(0), e(888))];
    let (proof, nf, cm_outs) = prove_spend(&note, position, amount, &outs);

    apply(
        &mut state,
        3,
        vec![StateMutation::Unshield {
            to: ALICE,
            amount: 10_000,
            anchor,
            nullifier: nf,
            cm_outs,
            proof,
        }],
    )
    .expect("an honest, proven unshield must be accepted");

    assert_eq!(state.balance_of(&ALICE, &NATIVE), 10_000, "value returned transparently");
    assert_eq!(state.shielded().value_locked(), 0, "pool drained of that note's value");
    assert!(state.shielded().is_spent(&nf), "nullifier consumed");
}

/// An unshield may never return more than the pool holds, even with a valid proof shape.
#[test]
fn unshield_cannot_overdraw_the_pool() {
    let (mut state, note, position, anchor) = shielded_fixture(10_000, 4242, 0xDEAD);
    // Prove a spend of the real note, then claim a LARGER withdrawal than it was worth.
    let amount = e(10_000);
    let outs = [(e(0), e(777)), (e(0), e(888))];
    let (proof, nf, cm_outs) = prove_spend(&note, position, amount, &outs);

    let err = apply(
        &mut state,
        3,
        vec![StateMutation::Unshield {
            to: ALICE,
            amount: 1_000_000, // a legal denomination, but the proof commits to 10_000
            anchor,
            nullifier: nf,
            cm_outs,
            proof,
        }],
    )
    .expect_err("SECURITY: withdrawing more than the proof commits to would mint");
    // The proof binds the public amount, so this is caught at verification.
    assert!(
        matches!(err, CommitError::ShieldedProofRejected { .. }),
        "got {err:?}"
    );
    assert_eq!(state.balance_of(&ALICE, &NATIVE), 0, "no credit on a refused unshield");
}

/// PERSISTENCE: the shielded pool must survive the snapshot round-trip.
///
/// The node persists state with `rmp_serde` (MessagePack). A pool that serialized but
/// came back wrong would be worse than one that failed to serialize: notes would silently
/// vanish, anchors would stop matching, and every honest spend would be rejected as
/// "unknown anchor" with nothing to point at. So this asserts the CONTENTS survive, not
/// merely that encode/decode returns Ok — and then re-verifies a real spend against the
/// restored anchor, which is the only proof that the restored pool is actually usable.
#[test]
fn shielded_pool_survives_the_snapshot_round_trip() {
    let (state, note, position, anchor) = shielded_fixture(10_000, 4242, 0xDEAD);

    let bytes = rmp_serde::to_vec(&state).expect("snapshot encode");
    let mut restored: SigilState = rmp_serde::from_slice(&bytes).expect("snapshot decode");

    let a = state.shielded();
    let b = restored.shielded();
    assert_eq!(b.len(), a.len(), "note count must survive");
    assert_eq!(b.note_at(0), a.note_at(0), "the note commitment itself must survive");
    assert_eq!(b.value_locked(), a.value_locked(), "locked value must survive");
    assert_eq!(b.nullifier_count(), a.nullifier_count(), "spent set must survive");
    assert!(
        b.is_known_anchor(&anchor),
        "the anchor window must survive — otherwise every pending spend fails as unknown-anchor"
    );
    assert_eq!(b.current_root(), a.current_root(), "the recomputed root must match");

    // The restored pool must be USABLE, not merely equal: prove a real spend against it.
    let fee = e(SHIELDED_FEE as u64);
    let outs = [(e(5_000), e(777)), (e(4_000), e(888))];
    let (proof, nf, cm_outs) = prove_spend(&note, position, fee, &outs);
    apply(
        &mut restored,
        3,
        vec![StateMutation::ShieldedSpend { anchor, nullifier: nf, cm_outs, fee: SHIELDED_FEE, proof, note_ciphertexts: vec![] }],
    )
    .expect("a spend must still verify against a restored anchor");
    assert!(restored.shielded().is_spent(&nf));
}

/// PRIVACY RULE: the fee is fixed, because a chosen fee is a fingerprint.
///
/// Amounts are hidden but the fee is public. If senders picked their own, a distinctive
/// value would identify them inside the anonymity set as reliably as a signature — the
/// crowd would be full of people wearing name tags.
#[test]
fn a_nonstandard_fee_is_refused() {
    let (mut state, note, position, anchor) = shielded_fixture(10_000, 4242, 0xDEAD);
    let odd = e(1_337); // distinctive, therefore identifying
    let outs = [(e(5_000), e(777)), (e(3_663), e(888))]; // still conserving
    let (proof, nf, cm_outs) = prove_spend(&note, position, odd, &outs);

    let err = apply(
        &mut state,
        3,
        vec![StateMutation::ShieldedSpend { anchor, nullifier: nf, cm_outs, fee: 1_337, proof, note_ciphertexts: vec![] }],
    )
    .expect_err("SECURITY: a chosen fee is a fingerprint and must be refused");
    assert!(matches!(err, CommitError::Shielded(_)), "got {err:?}");
    assert!(!state.shielded().is_spent(&nf), "a refused spend must not burn the nullifier");
}

/// PRIVACY RULE: ramps must use standard denominations.
///
/// The transparent side of a ramp names a wallet AND an amount, so shielding 7_431_902 and
/// unshielding 7_431_902 links the two without touching a single proof. This is the
/// cheapest attack on the whole design, and a coarse ladder is what defeats it.
#[test]
fn an_unusual_shield_amount_is_refused() {
    let mut state = SigilState::default();
    apply(
        &mut state,
        1,
        vec![StateMutation::SetBalance { wallet: ALICE, token: NATIVE, amount: 10_000_000 }],
    )
    .unwrap();

    let err = apply(
        &mut state,
        2,
        vec![StateMutation::Shield { from: ALICE, amount: 7_431_902, cm: [1u8; 32] }],
    )
    .expect_err("SECURITY: a correlatable amount must be refused at the ramp");
    assert!(matches!(err, CommitError::Shielded(_)), "got {err:?}");
    assert_eq!(state.shielded().len(), 0, "nothing may enter the pool");
    assert_eq!(state.balance_of(&ALICE, &NATIVE), 10_000_000, "and nothing was debited");

    // The same value IS shieldable when split into legal denominations.
    let parts = sigil_state::shielded::decompose(7_431_000).expect("decomposable");
    assert!(!parts.is_empty());
    assert_eq!(parts.iter().sum::<u128>(), 7_431_000);
    for (i, amt) in parts.iter().enumerate() {
        apply(
            &mut state,
            3 + i as u64,
            vec![StateMutation::Shield { from: ALICE, amount: *amt, cm: [(i as u8) + 2; 32] }],
        )
        .unwrap_or_else(|e| panic!("denomination {amt} must be accepted: {e}"));
    }
    assert_eq!(state.shielded().value_locked(), 7_431_000);
}

/// A REAL accumulated balance must be movable in full.
///
/// The first denomination ladder ran 10^3..10^9 and was chosen without ever checking it
/// against a balance on this chain. The master wallet holds 19,930,436,350,512 raw, which
/// at that ceiling needed 19,930 shield operations — and, because the balance is not a
/// multiple of 1,000, left 512 raw permanently stranded in the transparent domain. That is
/// not a privacy trade-off, it is a broken feature. This pins the fix.
#[test]
fn an_entire_accumulated_balance_can_be_shielded() {
    use sigil_state::shielded::decompose;
    const REAL_BALANCE: u128 = 19_930_436_350_512; // the live master wallet, to the unit

    let parts = decompose(REAL_BALANCE).expect("every integer amount must decompose");
    assert_eq!(
        parts.iter().sum::<u128>(),
        REAL_BALANCE,
        "SECURITY/UX: the decomposition must be EXACT — a stranded remainder is value the \
         owner can never make private"
    );
    assert!(
        parts.len() <= 32,
        "moving a whole balance must be practical, got {} operations",
        parts.len()
    );

    // And it actually lands, through the real chokepoint.
    let mut state = SigilState::default();
    apply(
        &mut state,
        1,
        vec![StateMutation::SetBalance { wallet: ALICE, token: NATIVE, amount: REAL_BALANCE }],
    )
    .unwrap();

    let muts: Vec<StateMutation> = parts
        .iter()
        .enumerate()
        .map(|(i, amount)| StateMutation::Shield {
            from: ALICE,
            amount: *amount,
            cm: to_wire(Note::new(*amount as u64, 1_000 + i as u64, 7).unwrap().commitment()),
        })
        .collect();
    apply(&mut state, 2, muts).expect("the whole balance must shield");

    assert_eq!(state.balance_of(&ALICE, &NATIVE), 0, "nothing left behind — no dust");
    assert_eq!(state.shielded().value_locked(), REAL_BALANCE, "all of it is private");
    assert_eq!(state.shielded().len(), parts.len());
}

/// THE POOL-GROWTH PATH: a miner registers once, and its rewards become pool notes.
///
/// This is the mechanism that grows the anonymity set without persuading anyone to change
/// their behaviour, so the properties worth pinning are that it is opt-in (an unregistered
/// wallet is untouched) and that a registered miner's reward really lands in the pool
/// rather than a transparent balance.
#[test]
fn a_registered_miner_is_paid_into_the_pool() {
    use sigil_shield::note_v1::coinbase_commitment_wire;

    const MINER: [u8; 32] = [0x77; 32];
    const UNREGISTERED: [u8; 32] = [0x88; 32];
    let acct = sigil_shield::wallet::ShieldedAccount::from_seed([0x77; 32]);
    let pk = to_wire(acct.public_key());

    let mut state = SigilState::default();
    apply(&mut state, 1, vec![StateMutation::RegisterShieldedAddress { wallet: MINER, pk_shield: pk, pk_encrypt: None }])
        .expect("registration");
    assert_eq!(state.shielded().shielded_address(&MINER), Some(pk));
    assert_eq!(
        state.shielded().shielded_address(&UNREGISTERED),
        None,
        "registration must be per-wallet and opt-in"
    );

    // A block reward for the registered miner.
    let reward: u128 = 201_881_165; // a real, non-round reward from the live chain
    let cm = coinbase_commitment_wire(2, &pk, reward).expect("in range");
    apply(&mut state, 2, vec![StateMutation::ShieldedCoinbase { pk_shield: pk, amount: reward, cm, ct: None }])
        .expect("shielded coinbase");

    assert_eq!(state.shielded().len(), 1, "ONE note per reward — no denomination split");
    assert_eq!(state.shielded().value_locked(), reward, "the reward is in the pool");
    assert_eq!(
        state.balance_of(&MINER, &NATIVE),
        0,
        "and NOT in a transparent balance — that is the whole point"
    );

    // The miner can recompute its own note from public data alone: no ciphertext needed.
    let recomputed = coinbase_commitment_wire(2, &pk, reward).unwrap();
    assert_eq!(
        state.shielded().note_at(0),
        Some(recomputed),
        "the miner must be able to FIND its reward from (height, pk) with no side channel"
    );
}

/// REPLAY: the live 2026-08-24/25 incident, at the chokepoint directly. `Shield` carries
/// no nullifier — unlike `ShieldedSend`/`Unshield`, which are proven safe against exactly
/// this above (`replaying_a_nullifier_is_refused`) — so nothing stopped the identical
/// signed `Shield{from, amount, cm, fee}` from landing a second time at a later height,
/// which is precisely what `sigil-api`'s pending-pool retry queue produces: it re-embeds
/// a not-yet-confirmed tx into every new candidate block until `confirm_applied` fires,
/// tens of minutes (hundreds of blocks) later. Live, this produced 513 duplicate
/// applications of a single 100-unit deposit before the retry queue's own age/attempt
/// cap finally gave up. This test is the two-heights minimal case that mechanism reduces
/// to: the SAME `StateMutation::Shield` landing at height 2 and again at height 3.
#[test]
fn replaying_a_shield_at_a_later_height_is_refused_not_double_applied() {
    let mut state = SigilState::default();
    apply(
        &mut state,
        1,
        vec![StateMutation::SetBalance { wallet: ALICE, token: NATIVE, amount: 100_000 }],
    )
    .expect("fixture funding");

    let cm = [0x42; 32];
    let shield = || StateMutation::Shield { from: ALICE, amount: 100, cm };

    // First landing — the honest, original application. Must behave exactly like any
    // other Shield (see `shielded_fixture`'s own assertions).
    apply(&mut state, 2, vec![shield()]).expect("the first application must succeed");
    assert_eq!(state.balance_of(&ALICE, &NATIVE), 100_000 - 100, "debited once");
    assert_eq!(state.shielded().value_locked(), 100, "locked once");
    assert_eq!(state.shielded().len(), 1, "one note");

    // Second landing at a LATER height: the exact same signed transaction, riding a
    // different, honestly-minted candidate block — not a different sender, not a forged
    // proof, just the producer's own retry queue re-embedding the identical payload.
    let err = apply(&mut state, 3, vec![shield()])
        .expect_err("SECURITY: a replayed Shield must be refused, not re-applied");
    assert!(
        matches!(
            err,
            CommitError::Shielded(sigil_state::shielded::ShieldedError::DuplicateCommitment(c))
                if c == cm
        ),
        "expected DuplicateCommitment({cm:02x?}), got {err:?}"
    );

    // THE ACTUAL BUG, pinned directly: state after the refused replay must be identical
    // to state after just the first, honest application. This also pins the mutation
    // ORDER inside the `Shield` arm — `append_note` (the fallible, now-duplicate-checked
    // call) must run BEFORE `lock_value`, or a rejected replay would still leave
    // `value_locked` incremented (the 21M supply-cap accounting silently drifting
    // upward on every refused replay attempt, forever, even though nothing was actually
    // debited or minted).
    assert_eq!(
        state.balance_of(&ALICE, &NATIVE),
        100_000 - 100,
        "a refused replay must not debit a second time"
    );
    assert_eq!(
        state.shielded().value_locked(),
        100,
        "a refused replay must not phantom-inflate locked value"
    );
    assert_eq!(state.shielded().len(), 1, "a refused replay must not mint a second note");
}

/// THE DISCOVERY GATE — a miner must be able to find its own shielded reward.
///
/// The test above asserts a miner "can recompute its own note from public data alone",
/// and hands `reward` straight to `coinbase_commitment_wire`. That is the assumption that
/// broke live on 2026-08-26: a real wallet does NOT know the amount. The commitment binds
/// `(height, pk_shield, amount)`, and the only record of `amount` was inside historical
/// block bodies — so with every note carrying no ciphertext (measured: 15,047 of 15,047)
/// and the apply path discarding `pk_shield`, a registered miner's rewards were real,
/// locked in the pool, and locatable only by scanning 2.24M blocks. An operator hit it as
/// "I mine and my balance never moves".
///
/// This asserts the fix from the WALLET's side, knowing only its own seed: open the
/// delivery ciphertext, recover `(value, blinding)`, and confirm the recovered value
/// reproduces the exact leaf sitting in the pool.
#[test]
fn a_miner_can_open_its_shielded_reward_knowing_only_its_seed() {
    const MINER: [u8; 32] = [0x99; 32];
    let seed = [0x99u8; 32];

    // Both keys come from the one seed a miner already backs up.
    let acct = sigil_shield::wallet::ShieldedAccount::from_seed(seed);
    let pk = to_wire(acct.public_key());
    let enc_id = sigil_shield::note_cipher::enc_identity_from_seed(&seed);
    let mut pk_enc = [0u8; 32];
    pk_enc.copy_from_slice(&hex::decode(enc_id.public_hex()).expect("hex"));

    let mut state = SigilState::default();
    apply(&mut state, 1, vec![StateMutation::RegisterShieldedAddress {
        wallet: MINER, pk_shield: pk, pk_encrypt: Some(pk_enc),
    }]).expect("registration");

    // Mint a reward exactly the way coinbase.rs now does: commitment + sealed delivery.
    let height = 2u64;
    let reward: u128 = 201_881_165;
    let cm = sigil_shield::note_v1::coinbase_commitment_wire(height, &pk, reward).expect("in range");
    let pk_field = sigil_shield::note_v1::from_wire(&pk).expect("pk");
    let pt = sigil_shield::note_cipher::NotePlaintext {
        value: reward as u64,
        blinding: sigil_shield::note_v1::coinbase_blinding(height, pk_field),
    };
    let addr = sigil_shield::note_cipher::ShieldedAddress::new(pk_field, &enc_id.public_hex());
    let ct = sigil_shield::note_cipher::seal_note(&pt, &addr).expect("seal").0;
    apply(&mut state, height, vec![StateMutation::ShieldedCoinbase {
        pk_shield: pk, amount: reward, cm, ct: Some(ct),
    }]).expect("shielded coinbase");

    // The ciphertext is stored in lockstep with the commitment.
    assert_eq!(state.shielded().len(), 1);
    let stored_ct = state.shielded().ciphertexts()[0].clone()
        .expect("a coinbase note must now carry a delivery ciphertext");

    // ── the wallet's side: it knows ONLY its seed ──
    let opened = sigil_shield::note_cipher::try_open_note(
        &sigil_shield::note_cipher::NoteCiphertext(stored_ct),
        &enc_id,
    ).expect("the recipient must be able to open its own note");

    assert_eq!(opened.value as u128, reward, "the wallet learns the amount it was paid");

    // And the recovered value reproduces the exact leaf — so it can be spent, not just seen.
    let rederived = sigil_shield::note_v1::coinbase_commitment_wire(height, &pk, opened.value as u128).expect("in range");
    assert_eq!(
        state.shielded().note_at(0), Some(rederived),
        "the opened note must reproduce the leaf in the pool"
    );

    // A DIFFERENT wallet's identity must not open it — the AEAD tag is the only gate.
    let stranger = sigil_shield::note_cipher::enc_identity_from_seed(&[0x11u8; 32]);
    let ct2 = state.shielded().ciphertexts()[0].clone().unwrap();
    assert!(
        sigil_shield::note_cipher::try_open_note(
            &sigil_shield::note_cipher::NoteCiphertext(ct2), &stranger).is_err(),
        "a note must not open for anyone but its recipient"
    );
}
