//! # sigil-spawn — the SIGIL chain-forge
//!
//! Turn a [`ChainSpec`] (26 knobs, all serde-settable) into a [`SpawnedChain`]:
//! a validated spec + a name-derived non-colliding [`ChainIdentity`] + a
//! [`Genesis`] commitment. Render it to a runnable scaffold, or spawn many at
//! once — identities never collide because they're derived from the name.
//!
//! ```
//! use sigil_spawn::{ChainSpec, SpawnedChain};
//! let chain = SpawnedChain::spawn(ChainSpec::new("Wickescoin", "WICK")).unwrap();
//! assert_eq!(chain.identity.address_prefix, "wick");
//! assert!(chain.genesis.hash.len() == 64);
//! ```

pub mod genesis;
pub mod identity;
pub mod spec;

pub use genesis::{emission_schedule, EmissionEra, Genesis};
pub use identity::ChainIdentity;
pub use spec::{Allocation, ChainSpec, PowAlgo, SpecError};

use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// A fully spawned chain: validated spec + derived identity + genesis.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SpawnedChain {
    pub spec: ChainSpec,
    pub identity: ChainIdentity,
    pub genesis: Genesis,
}

impl SpawnedChain {
    /// Validate the spec, then derive identity + genesis.
    pub fn spawn(spec: ChainSpec) -> Result<Self, SpecError> {
        spec.validate()?;
        let identity = ChainIdentity::derive(&spec);
        let genesis = Genesis::build(&spec, &identity);
        Ok(Self { spec, identity, genesis })
    }

    /// Human-readable one-screen summary.
    pub fn summary(&self) -> String {
        let s = &self.spec;
        let i = &self.identity;
        let eras = emission_schedule(s);
        let final_supply = eras.last().map(|e| e.cumulative).unwrap_or(0);
        format!(
            "⛓  {} ({})  •  PoW={:?}  •  decimals={}\n\
             network_id={}  magic={:#010x}  prefix={}\n\
             p2p={}  rpc={}  topics={}\n\
             max_supply={}  reward={}  halving={} blk  premine={}\n\
             emission eras={}  projected_supply={} ({:.2}% of cap)\n\
             genesis={}",
            s.name, s.ticker, s.pow_algo, s.decimals,
            i.network_id, i.network_magic, i.address_prefix,
            i.p2p_port, i.rpc_port, i.topics.len(),
            s.max_supply, s.initial_block_reward, s.halving_interval_blocks, s.premine_total(),
            eras.len(), final_supply,
            (final_supply as f64 / s.max_supply as f64) * 100.0,
            self.genesis.hash,
        )
    }

    /// Write a runnable scaffold into `out_dir/<network_id>/`:
    /// chainspec.json, genesis.json, node.toml, README.md. Returns paths written.
    pub fn render(&self, out_dir: impl AsRef<Path>) -> std::io::Result<Vec<PathBuf>> {
        let dir = out_dir.as_ref().join(&self.identity.network_id);
        std::fs::create_dir_all(&dir)?;
        let mut written = Vec::new();

        let chainspec = dir.join("chainspec.json");
        std::fs::write(&chainspec, self.spec.to_json())?;
        written.push(chainspec);

        let gen = dir.join("genesis.json");
        std::fs::write(&gen, serde_json::to_string_pretty(&self.genesis).unwrap())?;
        written.push(gen);

        let node_toml = dir.join("node.toml");
        std::fs::write(&node_toml, self.node_toml())?;
        written.push(node_toml);

        let readme = dir.join("README.md");
        std::fs::write(&readme, self.readme())?;
        written.push(readme);

        Ok(written)
    }

    fn node_toml(&self) -> String {
        let s = &self.spec;
        let i = &self.identity;
        format!(
            "# sigil-node config for {} ({}) — generated by sigil-spawn\n\
             [chain]\n\
             name = \"{}\"\n\
             ticker = \"{}\"\n\
             network_id = \"{}\"\n\
             network_magic = {}\n\
             genesis_hash = \"{}\"\n\
             pow_algo = \"{:?}\"\n\n\
             [net]\n\
             p2p_port = {}\n\
             rpc_port = {}\n\
             bootstrap_peers = {:?}\n\
             topics = {:?}\n\n\
             [economics]\n\
             decimals = {}\n\
             max_supply = {}\n\
             initial_block_reward = {}\n\
             halving_interval_blocks = {}\n\
             min_tx_fee = {}\n\
             dev_fee_bps = {}\n",
            s.name, s.ticker, s.name, s.ticker, i.network_id, i.network_magic,
            self.genesis.hash, s.pow_algo, i.p2p_port, i.rpc_port,
            s.bootstrap_peers, i.topics, s.decimals, s.max_supply,
            s.initial_block_reward, s.halving_interval_blocks, s.min_tx_fee, s.dev_fee_bps,
        )
    }

    fn readme(&self) -> String {
        format!(
            "# {} ({})\n\nSpawned with `sigil-spawn`. PoW chain on the SIGIL stack.\n\n\
             - **network_id**: `{}`\n- **genesis**: `{}`\n- **P2P**: `{}`  **RPC**: `{}`\n\n\
             ## Run\n```bash\nsigil-node --config node.toml\n```\n\n\
             ## Files\n- `chainspec.json` — the full 26-knob spec\n\
             - `genesis.json` — genesis commitment\n- `node.toml` — node runtime config\n",
            self.spec.name, self.spec.ticker, self.identity.network_id,
            self.genesis.hash, self.identity.p2p_port, self.identity.rpc_port,
        )
    }
}

/// Spawn many chains at once. Identities are non-colliding by name-derivation,
/// so you can stand up a whole fleet of PoW chains in one call.
pub fn spawn_many(specs: Vec<ChainSpec>) -> Result<Vec<SpawnedChain>, SpecError> {
    specs.into_iter().map(SpawnedChain::spawn).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_spec_spawns_and_validates() {
        let c = SpawnedChain::spawn(ChainSpec::new("Wickescoin", "WICK")).unwrap();
        assert_eq!(c.identity.address_prefix, "wick");
        assert_eq!(c.genesis.hash.len(), 64);
        assert_eq!(c.identity.network_id.len(), 16);
        assert_eq!(c.identity.topics.len(), 3);
    }

    #[test]
    fn distinct_names_yield_non_colliding_identities() {
        let a = SpawnedChain::spawn(ChainSpec::new("Alpha", "ALFA")).unwrap();
        let b = SpawnedChain::spawn(ChainSpec::new("Bravo", "BRVO")).unwrap();
        assert_ne!(a.identity.network_id, b.identity.network_id);
        assert_ne!(a.identity.network_magic, b.identity.network_magic);
        assert_ne!(a.identity.p2p_port, b.identity.p2p_port);
        assert_ne!(a.identity.topics, b.identity.topics);
        assert_ne!(a.genesis.hash, b.genesis.hash);
    }

    #[test]
    fn supply_cap_is_enforced() {
        let mut s = ChainSpec::new("Toomuch", "TMC");
        s.max_supply = 1000; // far below the ~21M*unit emission
        let err = SpawnedChain::spawn(s).unwrap_err();
        assert!(matches!(err, SpecError::SupplyExceedsCap { .. }));
    }

    #[test]
    fn premine_counts_against_cap() {
        let mut s = ChainSpec::new("Pre", "PRE");
        // shrink emission so only premine matters, then overshoot with premine
        s.initial_block_reward = s.unit();
        s.halving_interval_blocks = 1;
        s.max_supply = 10 * s.unit();
        s.premine = vec![Allocation { address: "pre1xxx".into(), amount: 100 * s.unit() }];
        assert!(matches!(SpawnedChain::spawn(s).unwrap_err(), SpecError::SupplyExceedsCap { .. }));
    }

    #[test]
    fn emission_schedule_stays_under_cap_for_default() {
        let s = ChainSpec::new("Cap", "CAP");
        let eras = emission_schedule(&s);
        let final_supply = eras.last().unwrap().cumulative;
        assert!(final_supply <= s.max_supply, "halving emission must fit under cap");
        assert!(eras.len() > 20, "should have many halving eras");
    }

    #[test]
    fn json_roundtrip() {
        let s = ChainSpec::new("Json", "JSON");
        let back = ChainSpec::from_json(&s.to_json()).unwrap();
        assert_eq!(s, back);
    }

    #[test]
    fn spawn_many_and_render() {
        let specs = vec![
            ChainSpec::new("One", "ONE"),
            ChainSpec::new("Two", "TWO"),
            ChainSpec::new("Three", "THREE"),
        ];
        let chains = spawn_many(specs).unwrap();
        assert_eq!(chains.len(), 3);
        // all network_ids distinct
        let mut ids: Vec<_> = chains.iter().map(|c| c.identity.network_id.clone()).collect();
        ids.sort();
        ids.dedup();
        assert_eq!(ids.len(), 3);

        // render the first into a tmpdir
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("sigil-spawn-test-{}", nanos));
        let files = chains[0].render(&dir).unwrap();
        assert_eq!(files.len(), 4);
        assert!(files.iter().all(|f| f.exists()));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
